### ISSUE TITLE
Difi.SikkerDigitalPost.Klient.Domene.Exceptions.SdpSecurityException

### ISSUE THREAD

**Issue by skathayat** [difi/sikker-digital-post-klient-dotnet#140]
Prøvde å sende Digipost (HEMIT test Bruker - 26129316763). Men fikk følgende unntak. 
Kildecoden er vedlagt. Unntak på linje 140 i den vedlagte filen.
<code>Transportkvittering transportkvittering = await _sikkerDigitalPostKlient.SendAsync(forsendelse);</code>

    [TestMethod]
    public void TestDIfi_SendPost()
    {
      try
      {
        string pNumber = DifiHelperUtil.test_bruker_hemit_10;
        string avsenderOrgnr = DifiHelperUtil.orgNr_StOlavHospitalHF;
        DifiSikkerDigitalPostClientProxy postClient = new DifiSikkerDigitalPostClientProxy(pNumber, avsenderOrgnr);
        // set sending dokument related
        string hovedDokument = "c:\\temp\\Hoveddokument.pdf";
        List<string> attachments = new List<string>();
        attachments.Add("c:\\temp\\Vedlegg.txt");
        string postTitle = "Post title";
        postClient.SendPost(hovedDokument, attachments, postTitle);
      }
      catch (Exception ex)
      {
        throw;
      }
    }

---------------------Exception-----------------------
Difi.SikkerDigitalPost.Klient.Domene.Exceptions.SdpSecurityException was unhandled by user code
  HResult=-2146233088
  **Message=Kan ikke finne påkrevet element '/env:Envelope/env:Header/wsse:Security/wsu:Timestamp' i svar fra meldingsformidler.**
  Source=Difi.SikkerDigitalPost.Klient
  StackTrace:
       at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ResponsInneholderPåkrevdeNoder(String elementXPath, XmlNodeList& nodes)
       at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderSignaturelementer()
       at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderHeaderSignatur()
       at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderTransportkvittering(GuidUtility guidUtility)
       at Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.SikkerhetsvalideringAvTransportkvittering(XmlDocument kvittering, XmlDocument forretningsmelding, GuidUtility guidUtility)
       at Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.<SendAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Hemit.BizTalk.DifiHelper.DifiSikkerDigitalPostClientProxy.<SendPostAsync>d__0.MoveNext() in \\hemitbrukere.helsemn.no\home$\surkat-he\Dokumenter\Visual Studio 2013\Projects\Hemit.BizTalk.DifiHelper\Hemit.BizTalk.DifiHelper\DifiSikkerDigitalPostClientProxy.cs:line 140
  InnerException: 

[DifiSikkerDigitalPostClientProxy.pdf](https://github.com/difi/sikker-digital-post-klient-dotnet/files/44823/DifiSikkerDigitalPostClientProxy.pdf)

**Comment by asjafjell** [comment]
Hei, @skathayat!

Takk for tilbakemelding. Kan du sende koden som en [gist](https://gist.github.com/) eller lignende, så vi kan få testet koden?

**Comment by skathayat** [comment]
Hei @asjafjell 

gist ligger her: https://gist.github.com/skathayat/7523e0a9347bb7b4fd10

Takk.

**Comment by skathayat** [comment]
Hei @asjafjell 

Her er en enklere versjon, bare en enkelt fil. Samme feil melding.

https://gist.github.com/skathayat/32b53a475e505b2c8a44

Meldingsformidleresponse er vedlagt her.

![difierror](https://cloud.githubusercontent.com/assets/1191568/11438729/17399a42-94f7-11e5-8ea8-2968dc45a3be.png)

**Comment by kristianenge** [comment]
Takker for mer info @skathayat ! Kunne du lastet opp meldingsformidlerresponsen som en gist også?

**Comment by kristianenge** [comment]
Feilen du opplever er at sertifikatet du bruker og orgnummer du setter i `Databehandler` ikke matcher. Du kan forsøke å endre dette og se om det hjelper. 

Jeg sjekker ut hvorfor klienten ikke klarer å parse denne spesifikke transportkvitteringen. Gir status fortøpende.

**Comment by skathayat** [comment]
Hei @kristianenge @asjafjell 
Takk for hjelpen. Fikk TransportOkKvittering nå.
Men, der er en feilmelding med kvittering, som er vedlagt.
Mottaker 26129316763 er registret i DIgipost. Bør vi registrere avsender orgnr i Digipost også?

![feil_kvittering](https://cloud.githubusercontent.com/assets/1191568/11466903/e8965aa4-9744-11e5-8bd5-1271571d8f3c.png)

**Comment by aberner** [comment]
Dette fikser jeg og følger opp direkte med @skathayat 
så den opprinnelige feilen er løst ok.

så denne saken følges nå opp av @kristianenge som skrev: "Jeg sjekker ut hvorfor klienten ikke klarer å parse denne spesifikke transportkvitteringen. Gir status fortløpende."

**Comment by asjafjell** [comment]
Løst i versjon 1.5.
